Dynamic validation
aartikov/Sesame pull request #43
Opened 2021-11-22 13:21 UTC by developer-kaczmarek

2021-11-23 11:16 UTC, aartikov requested changes

2021-11-23 11:16 UTC, aartikov commented on compose-sample/src/main/kotlin/me/aartikov/sesamecomposesample/menu/MenuButton.kt
> -    modifier: Modifier = Modifier
у Modifier было правильное положение: первый необязательный аргумент

2021-11-23 11:16 UTC, aartikov commented on sesame-compose-form/src/main/kotlin/me/aartikov/sesame/compose/form/control/InputControl.kt
> +    var hasFocus = MutableStateFlow(false)
Лучше вернуть как было, все остальные поля используют композовский MutableState-делегат, значит и это должно.

2021-11-23 11:16 UTC, aartikov commented on sesame-compose-form/src/main/kotlin/me/aartikov/sesame/compose/form/control/InputControl.kt
> +    override val skipInValidationChangeEvent = MutableStateFlow(false)
valueChangeEvent, skipInValidationChangeEvent - называются "Event", а по факту стейт (поскольку используется Mutable**State**Flow). Явно что-то не то.

Кроме того, они, похоже, совсем не нужны, ведь уже есть поля value и skipInValidation с такими же значениями

2021-11-23 11:16 UTC, aartikov commented on sesame-compose-form/src/main/kotlin/me/aartikov/sesame/compose/form/control/ValidatableControl.kt
> +    val skipInValidationChangeEvent: MutableStateFlow<Boolean>
Уже есть поля value и skipInValidation

2021-11-23 11:16 UTC, aartikov commented on sesame-compose-form/src/main/kotlin/me/aartikov/sesame/compose/form/validation/form/DynamicValidationResult.kt
> +}
Нужно переписать используя snapshotFlow

Кажется, так. Но надо проверять:
```
snapshotFlow { control.value to control.skipInValidation }
  .drop(1)
  .onEach {
     callback()
  }
  .launchIn(coroutineScope)
```

2021-11-23 11:16 UTC, aartikov commented on sesame-compose-form/src/main/kotlin/me/aartikov/sesame/compose/form/validation/form/FormValidationFeature.kt
>  }
Использовать snapshotFlow для реализации всех FormValidationFeature

2021-11-24 06:23 UTC, developer-kaczmarek commented on compose-sample/src/main/kotlin/me/aartikov/sesamecomposesample/menu/MenuButton.kt
> -    modifier: Modifier = Modifier
Если бы он оставался на прежнем месте, то стал бы притягивать внимание со следующим сообщением :Modifier parameter should be the first optional parameter. Поэтому могу просто поднять вышe colors

2021-11-24 08:19 UTC, aartikov requested changes

2021-11-24 08:19 UTC, aartikov commented on compose-sample/src/main/kotlin/me/aartikov/sesamecomposesample/form/FormUi.kt
> +    }
В документации написано, что блок update может быть вызван несколько раз из-за рекомпозиции. Это значит, что мы подпишемся на флоу несколько раз, что нежелательно.

Правильнее будет перенести это в блок factory.

2021-11-24 08:19 UTC, aartikov commented on compose-sample/src/main/kotlin/me/aartikov/sesamecomposesample/form/RealFormComponent.kt
> +    private val dynamicResult = coroutineScope.dynamicValidationResult(formValidator)
Используем `by` вместо `=`, чтоб не писать `.value`

2021-11-24 08:19 UTC, aartikov commented on compose-sample/src/main/kotlin/me/aartikov/sesamecomposesample/form/RealFormComponent.kt
> +    private val channel = Channel<Unit>(Channel.UNLIMITED)
channel  -> dropKonfettiChannel

2021-11-25 07:35 UTC, merged